### ISSUE TITLE
Ask for confirmation

### ISSUE THREAD

**Issue by lrkwz** [layershift/jelastic-cli#1]
Launching the container requires confirmation on sending errors despite of 

    jelastic.cli.send_err_confirm=false

**Comment by bubbl** [comment]
Thanks for applying those changes!

**Comment by lrkwz** [comment]
You're welcome, will you redeploy the image to hub.docker?
Why don't you configure the automated build? it will automagically rebuild
when commits are pushed to github

*=> Luca <http://stackexchange.com/users/239746>*



2017-02-08 12:35 GMT+01:00 Bart Bania <notifications@github.com>:

**Comment by bubbl** [comment]
We'll create an automated build instead of this repo.

Initially it was set like that think by pure chance and I was using jenkins to push changes.

**Comment by bubbl** [comment]
In fact, automated build was just added and first build is being triggered. 

I agree, it would be a better path for updating the image.
